a = int(input())
b = int(input())
c = ('Summa ravna', a+b)
print(c)
d = ('Raznost ravna', a - b)
print(d)
e = ('Proizvedenie ravno', a*b)
print(e)
f = ('Stepen a v b eto', a**b)
print(f)
g = ('Modul =', (abs(a / b)))
print(g)
h = ('Celochislennym budet', a // b)
print(h)